name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip openjdk-17-jdk
          pip install buildozer cython

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Build Tools
        run: sdkmanager "platform-tools" "platforms;android-31" "build-tools;30.0.3"

      - name: Build Release APK
        run: buildozer -v android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
